name: edu_sync
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  shared_preferences: ^2.3.2
  flutter_heatmap_calendar: ^1.0.5
  flutter_svg: ^2.0.10+1
  mailer: ^6.2.0
  cached_network_image: ^3.2.1
  http: ^1.2.2
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  table_calendar: ^3.1.2
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  permission_handler: ^11.3.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/MainIcons/
    - assets/gifs/
